---
- name: Install Apache on web server
  hosts: app
  become: true
  become_user: root

  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start Apache
      ansible.builtin.service:
        name: httpd
        state: started